export const APP_TEXT = {
  auth: {
    errors: {
      tryAgain: 'Try again.',
      sendOtpFailed: 'Could not send OTP',
      verifyFailed: 'Verification failed',
      resendFailed: 'Resend failed',
      onboardingFailed: 'Onboarding failed',
    },
    phoneLogin: {
      title: 'Welcome to Dellite!',
      subtitle: 'Enter your phone number to get started with home services in Prayagraj',
      countryCode: 'IN +91',
      phonePlaceholder: '8888888888',
      sendOtpButton: 'Send OTP',
      securePrivate: 'Secure & Private',
      noSpam: 'No Spam',
      terms: 'By continuing, you agree to our Terms of Service & Privacy Policy',
    },
    otpVerification: {
      title: 'Verify Your Number',
      codeSentPrefix: "We've sent a 4-digit code to ",
      resendPrefix: 'Resend code in ',
      resendSuccessTitle: 'OTP sent',
      resendSuccessMessage: 'A new OTP has been sent to your phone.',
      verifyButton: 'Verify & Continue',
      helpText: "Didn't receive the code? Check your SMS inbox or try resending",
    },
  },
  onboarding: {
    identity: {
      step: 'STEP 1 OF 3',
      titlePrefix: 'Tell us about',
      gradientWord: 'yourself',
      subtitle: "We'll personalize your experience based on this info",
      uploadPhotoTitle: 'Add profile photo',
      uploadPhotoSubtitle: 'You can upload your picture in the next update.',
      firstNameLabel: 'First Name',
      firstNamePlaceholder: 'First Name',
      lastNameLabel: 'Last Name',
      lastNamePlaceholder: 'Last Name',
      genderLabel: 'Gender',
      nextButton: 'Next',
    },
    vehicle: {
      step: 'STEP 2 OF 3',
      title: 'Choose your services',
      subtitle: 'Select services you can provide in your city',
      searchPlaceholder: 'Search categories...',
      saveServicesButton: 'Save Selected Services',
      certificatesTitle: 'Certificates Required',
      certificatesSubtitle: 'Some selected services need certificates before approval.',
      continueButton: 'Continue',
      noCertificateText: 'No certificate required for selected services.',
      selectedCountSuffix: 'services selected',
    },
    certification: {
      step: 'STEP 3 OF 3',
      title: 'Certificates Required',
      subtitle: 'Upload required certificates to complete onboarding.',
      continueButton: 'I Have Uploaded Certificates',
      noCertificateText: 'No certificate is currently required. Continue to refresh status.',
    },
    welcome: {
      step: 'STEP 3 OF 3',
      title: "All set! You're ready",
      subtitle: 'Profile and services are saved. You can now start receiving jobs.',
      button: 'Start Getting Jobs',
    },
  },
  tabs: {
    homeLabel: 'Home',
    ongoingLabel: 'Ongoing',
    earningsLabel: 'Earnings',
    profileLabel: 'Profile',
  },
  home: {
    title: 'Home',
    welcomePrefix: 'Welcome, ',
    welcomeFallbackName: 'Partner',
    welcomeSuffix: '.',
    subtitle: 'Daily summary, quick actions, and assigned tasks will appear here.',
  },
  ongoing: {
    title: 'Ongoing',
    subtitle: 'Active orders, route progress, and live task updates will show here.',
  },
  earnings: {
    title: 'Earnings',
    subtitle: 'Weekly earnings, payout status, and transaction history will be listed here.',
  },
  profile: {
    title: 'Profile',
    phoneLabel: 'Phone:',
    nameLabel: 'Name:',
    phoneFallback: 'Not available',
    nameFallback: 'Not set',
    editProfileButton: 'Edit Profile',
    payoutDetailsButton: 'Payout Details',
    helpSupportButton: 'Help & Support',
    logoutButton: 'Logout',
    edit: {
      title: 'Edit Profile',
      fullNamePlaceholder: 'Full Name',
      emailPlaceholder: 'Email Address',
      saveButton: 'Save Changes',
    },
    payout: {
      title: 'Payout Details',
      accountPlaceholder: 'Bank Account Number',
      ifscPlaceholder: 'IFSC Code',
      updateButton: 'Update Payout',
    },
    helpSupport: {
      title: 'Help & Support',
      subtitle: 'Support chat, FAQs, and contact channels can be added here.',
    },
  },
} as const;
